### PR TITLE
 Add `serde` integration via a new feature called `serde-integration` 

### PR DESCRIPTION
**Pull request by ErichDonGubler**

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
I've learned since filing this PR that it's possible to actually just make `serde` an optional dependency and allow downstream crates to request a feature called `serde`. Neat! I'm more than happy to fix it to be that way if you want.

**Comment by Kloenk** [comment]
Yes, I think renaming it to `serde`, would create better readability.

Also I would like to have serde as the last entry (maybe even with a newline between) in the cargo.toml, as it is a optional dependency.

**Comment by ErichDonGubler** [comment]
@Kloenk: I've force-pushed some changes; the path to having a feature called `serde` seemed to be best implemented as a separate `dependencies.serde_crate` block anyway, so I think all feedback has been satisfied?

**Comment by Kloenk** [comment]
This does not build on my device:
~~~
[nix-shell:~/nyantec/rust-journald]$ cargo build --features serde
   Compiling journald v0.6.0 (/persist/data/kloenk/nyantec/rust-journald)
error[E0463]: can't find crate for `serde`
 --> src/journal_entry.rs:6:38
  |
6 | #[cfg_attr(feature = "serde", derive(Deserialize, Serialize))]
  |                                      ^^^^^^^^^^^ can't find crate
  |
  = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `journald`

To learn more, run the command again with --verbose.

**Comment by Kloenk** [comment]
Looking at the backtrace I could think that this is a rust 2015 error. I can update it to 2018 tomorrow.

**Comment by Kloenk** [comment]
> Optional dependencies implicitly define a feature of the same name as the dependency.

So the dependency can be named serde, so the macro does not break.

**Comment by Kloenk** [comment]
@ErichDonGubler I resolved the merge conflict, and renamed the dependency. Please look over those changes.

**Comment by ErichDonGubler** [comment]
If this compiles, LGTM! I apologize for pushing breaks -- I thought I had done changes correctly, but didn't/don't have a Linux machine immediately available for testing.

**Pull request merged**
